export const API_END_POINTS = {
    BUDGET_CATEGORY:'/budgetCategory/budgetCategory',
    SUB_CATEGORY:'/subCategory/subCategory',
    VENDOR:'/vendor/vendor',
    CREATE_BUDGET:'/createbudget',
    BUDGET_CATEGORY_DETAILS:'/budgetCategoryDetails',
    BUDGET_CATEGORY_LIST:'/budgetCategory/findAllBudgetCategory',
    BUDGET_SUB_CATEGORY_LIST:'/subCategory/findAllBudgetSubCategory',
    VENDOR_NAME_LIST:'/vendor/findAllVendor',
    BUDGET_CODE_LIST:'/findAllCodeList',
    EDIT_CATEGORY:'/budgetCategory/',
    EDIT_SUB_CATEGORY:'/subCategory/',
    EDIT_VENDOR:'/vendor/',
    DELETE_CATEGORY:'/budgetCategory/',
    DELETE_SUB_CATEGORY:'/subCategory/',
    DELETE_VENDOR:'/vendor/',
}
