export const API_END_POINTS = {
    // VENDOR: '/vendor/vendor',
    // BUDGET_CATEGORY:'/budgetCategory/budgetCategory',
    // SUBCATEGORY:'/subCategory/subCategory',
    // BUDGETCATEGORYLIST:'budgetCategory/findAllBudgetCategory',
    // BUDGETSUBCATEGORYLIST:'/findAllSubBudgetCategory',
    // CREATEBUDGET:'/createbudget',
    // VENDORNAMELIST:'/findAllVendor',
    // BUDGETCATEGORYDETAILS:'/budgetCategoryDetails',
    // DELETECATEGORY:'/deleteCategory',
    // BUDGETCODELIST:'/findAllCodeList'
    VENDOR:'/vendor/vendor',
    BUDGET_CATEGORY:'/budgetCategory/budgetCategory',
    EDITCATEGORY:'/budgetCategory/',
    EDITSUBCATEGORY:'/subCategory/',
    SUBCATEGORY:'/subCategory/subCategory',
    BUDGETCATEGORYLIST:'/budgetCategory/findAllBudgetCategory',
    BUDGETSUBCATEGORYLIST:'/subCategory/findAllBudgetSubCategory',
    CREATEBUDGET:'/createbudget',
    VENDORNAMELIST:'/vendor/findAllVendor',
    DELETEVENDOR:'/vendor/',
    BUDGETCATEGORYDETAILS:'/budgetCategoryDetails',
    DELETECATEGORY:'/budgetCategory/',
    BUDGETCODELIST:'/findAllCodeList',
    DELETESUBCATEGORY:'/subCategory/',
    
}
